name: GodWar
author: alvin0319
main: alvin0319\GodWar\GodWar
version: 1.0.0
api: 3.0.0

mcpe-protocol: 408

permissions:
  godwar.*:
    description: GodWar permission
    children:
      godwar.command:
        description: GodWar command permission
        default: op