# default is plugin's world, you need to replace here if you want to change world.
world-zip: world.zip

# It is time for the game to progress, default: 2000 (seconds)
time: 2000


# The number of rooms to be created.
room: 2

# The number of min player count.
min-count: 4
# The number of max player count, MUST larger than min count.
max-count: 8

red-spawn: "504:62:115:godwar_0"
blue-spawn: "504:62:-105:godwar_0"